const australianSpellings: [string, string][] = [
  ["analyzers", "analysers"],
  ["analyzer", "analyser"],
  ["analyzing", "analysing"],
  ["analyzed", "analysed"],
  ["analyzes", "analyses"],
  ["analyze", "analyse"],
  ["summarizers", "summarisers"],
  ["summarizer", "summariser"],
  ["summarizing", "summarising"],
  ["summarized", "summarised"],
  ["summarizes", "summarises"],
  ["summarize", "summarise"],
  ["organizations", "organisations"],
  ["organization", "organisation"],
  ["organizers", "organisers"],
  ["organizer", "organiser"],
  ["organizing", "organising"],
  ["organized", "organised"],
  ["organizes", "organises"],
  ["organize", "organise"],
  ["optimizations", "optimisations"],
  ["optimization", "optimisation"],
  ["optimizers", "optimisers"],
  ["optimizer", "optimiser"],
  ["optimizing", "optimising"],
  ["optimized", "optimised"],
  ["optimizes", "optimises"],
  ["optimize", "optimise"],
  ["maximization", "maximisation"],
  ["maximizing", "maximising"],
  ["maximized", "maximised"],
  ["maximizes", "maximises"],
  ["maximize", "maximise"],
  ["customization", "customisation"],
  ["customizing", "customising"],
  ["customized", "customised"],
  ["customizes", "customises"],
  ["customize", "customise"],
  ["recognizable", "recognisable"],
  ["recognizing", "recognising"],
  ["recognized", "recognised"],
  ["recognizes", "recognises"],
  ["recognize", "recognise"],
  ["prioritization", "prioritisation"],
  ["prioritizing", "prioritising"],
  ["prioritized", "prioritised"],
  ["prioritizes", "prioritises"],
  ["prioritize", "prioritise"],
  ["visualization", "visualisation"],
  ["visualizing", "visualising"],
  ["visualized", "visualised"],
  ["visualizes", "visualises"],
  ["visualize", "visualise"],
  ["personalization", "personalisation"],
  ["personalizing", "personalising"],
  ["personalized", "personalised"],
  ["personalizes", "personalises"],
  ["personalize", "personalise"],
  ["humanizing", "humanising"],
  ["humanized", "humanised"],
  ["humanizes", "humanises"],
  ["humanize", "humanise"],
  ["stylizing", "stylising"],
  ["stylized", "stylised"],
  ["stylizes", "stylises"],
  ["stylize", "stylise"],
  ["symbolizing", "symbolising"],
  ["symbolized", "symbolised"],
  ["symbolizes", "symbolises"],
  ["symbolize", "symbolise"],
  ["monetization", "monetisation"],
  ["monetizing", "monetising"],
  ["monetized", "monetised"],
  ["monetizes", "monetises"],
  ["monetize", "monetise"],
  ["behaviors", "behaviours"],
  ["behavioral", "behavioural"],
  ["behavior", "behaviour"],
  ["favorites", "favourites"],
  ["favorited", "favourited"],
  ["favorite", "favourite"],
  ["colorless", "colourless"],
  ["colorful", "colourful"],
  ["watercolors", "watercolours"],
  ["watercolor", "watercolour"],
  ["coloring", "colouring"],
  ["colored", "coloured"],
  ["colors", "colours"],
  ["color", "colour"],
  ["centered", "centred"],
  ["gray", "grey"],
  ["artifacts", "artefacts"],
  ["artifact", "artefact"],
  ["catalogs", "catalogues"],
  ["catalog", "catalogue"],
];

function matchCase(source: string, replacement: string) {
  if (source === source.toUpperCase()) return replacement.toUpperCase();
  if (source[0] === source[0]?.toUpperCase()) {
    return replacement[0].toUpperCase() + replacement.slice(1);
  }
  return replacement;
}

export function normaliseAustralianEnglish(value: string) {
  return australianSpellings.reduce(
    (text, [us, au]) =>
      text.replace(new RegExp(`\\b${us}\\b`, "gi"), (match) => matchCase(match, au)),
    value,
  );
}
